// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: owner.sql

package db

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO owners (
  name,
  email,
  phone
) VALUES (
  $1, $2, $3
) RETURNING id, name, email, phone, created_at
`

type CreateAccountParams struct {
	Name  string `json:"name"`
	Email string `json:"email"`
	Phone string `json:"phone"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Owners, error) {
	row := q.db.QueryRowContext(ctx, createAccount, arg.Name, arg.Email, arg.Phone)
	var i Owners
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
	)
	return i, err
}
